---
# Role configuration tasks

- block:
    - name: Gather options facts
      set_fact:
        _sshd_options_map: >-
          {{ lookup('template', 'sshd_options_map.yml.j2') | from_yaml }}

        _sshd_main_options: >-
          {{ lookup('template', 'sshd_main_options.yml.j2') | from_yaml }}

        _sshd_rules_options: >-
          {{ lookup('template', 'sshd_rules_options.yml.j2') | from_yaml }}

    - name: Configure sshd
      template:
        backup: yes
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0600
      notify: reload sshd

    - name: Gather service facts
      service_facts:

    - name: Verify that sshd config is valid
      command: /usr/sbin/sshd -t
      register: sshd_test_config_result
      failed_when: sshd_test_config_result.rc != 0
      changed_when: no
      when: >-
        ansible_facts.services["sshd.service"]["state"]
        | default("") == "running"
        or ansible_facts.services["sshd"]["state"]
           | default("") == "running"
  tags:
    - role::sshd
    - role::sshd::configure
