---
# Install tasks

- name: Create directory for sshd include files
  file:
    path: "{{ sshd_conf_d_dir }}"
    state: directory
    owner: root
    group: root
    mode: "u=rw"
  tags:
    - role::sshd
    - role::sshd::install
