---
# Role install tasks

- name: install sshd packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ sshd_packages[ansible_distribution | lower] }}"

- name: create directory for sshd include files
  file:
    path: "{{ sshd_conf_d_dir }}"
    state: directory
    owner: root
    group: root
    mode: "u=rw"
