---
# Role tasks

- name: install sshd daemon
  import_tasks: install.yml
  tags:
    - role::sshd
    - role::sshd::install

- name: configure sshd daemon
  import_tasks: configure.yml
  tags:
    - role::sshd
    - role::sshd::configure

- name: setup sshd service
  import_tasks: service.yml
  tags:
    - role::sshd
    - role::sshd:service
