---
# Handlers

- name: sshd reload
  service:
    name: sshd
    state: reloaded
  listen:
    - reload sshd
  when: sshd_reload
  tags:
    - role::sshd
    - role::sshd::service

- name: sshd restart
  service:
    name: sshd
    state: restarted
  when: sshd_restart
  listen:
    - restart sshd
  tags:
    - role::sshd
    - role::sshd::service
