---

- name: Sshd reload
  ansible.builtin.service:
    name: sshd
    state: reloaded
  listen:
    - reload sshd
  when: sshd_reload | bool
  tags:
    - role::sshd
    - role::sshd::service

- name: Sshd restart
  ansible.builtin.service:
    name: sshd
    state: restarted
  when: sshd_restart | bool
  listen:
    - restart sshd
  tags:
    - role::sshd
    - role::sshd::service
