---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    image: centos:6
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: centos:8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora33-${INSTANCE_UUID:-1}"
    image: fedora:33
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: fedora:34
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          sshd_protocol_version: 2
          sshd_port: 22
          sshd_address_family: any
          sshd_listen_addresses:
            - 0.0.0.0
            - "::"
          sshd_tcp_keep_alive: yes
          sshd_client_alive_interval: 0
          sshd_client_alive_count_max: 3
          sshd_compression: delayed
          sshd_use_dns: no
          sshd_banner: /etc/issue.net
          sshd_print_motd: yes
          sshd_print_last_log: yes
          sshd_hostkey_files:
            - /etc/ssh/ssh_host_rsa_key
            - /etc/ssh/ssh_host_ecdsa_key
            - /etc/ssh/ssh_host_ed25519_key
          sshd_syslog_facility: AUTHPRIV
          sshd_log_level_type: INFO
          sshd_login_grace_time: 60
          sshd_permit_root_login: yes
          sshd_strict_modes: yes
          sshd_max_auth_tries: 3
          sshd_max_sessions: 10
          sshd_pubkey_authentication: yes
          sshd_authorized_keys_file: .ssh/authorized_keys
          sshd_host_based_authentication: no
          sshd_ignore_known_hosts: no
          sshd_ignore_rhosts_file: yes
          sshd_permit_empty_passwords: no
          sshd_password_authentication: yes
          sshd_challenge_response_authentication: no
          sshd_kerberos_authentication: no
          sshd_kerberos_or_local_passwd: yes
          sshd_kerberos_ticket_cleanup: yes
          sshd_kerberos_use_k_user_ok: yes
          sshd_gssapi_authentication: yes
          sshd_gssapi_cleanup_credentials: no
          sshd_gssapi_strict_accept_or_check: yes
          sshd_gssapi_key_exchange: no
          sshd_use_pam: yes
          sshd_allow_agent_forwarding: yes
          sshd_allow_tcp_forwarding: no
          sshd_gateway_ports: no
          sshd_permit_tunnel: no
          sshd_x11_forwarding: no
          sshd_x11_display_offset: 10
          sshd_x11_use_local_host: yes
          sshd_use_login: no
          sshd_permit_user_environment: no
          sshd_pid_file: /var/run/sshd.pid
          sshd_max_startups: "10:30:100"
          sshd_ciphers:
            - aes256-ctr
            - aes192-ctr
            - aes128-ctr
          sshd_macs:
            - hmac-sha2-512
            - hmac-sha2-256
          sshd_allowed_users:
            - root
          sshd_allowed_groups:
            - root
            - users
          sshd_denied_users:
            - acme
          sshd_denied_groups:
            - acme
          sshd_accept_env:
            - LANG
            - LC_CTYPE
            - LC_NUMERIC
            - C_TIME
            - LC_COLLATE
            - LC_MONETARY
            - LC_MESSAGES
            - LC_PAPER
            - LC_NAME
            - LC_ADDRESS
            - LC_TELEPHONE
            - LC_MEASUREMENT
            - LC_IDENTIFICATION
            - LC_ALL LANGUAGE
            - XMODIFIERS
          sshd_subsystems:
            - name: sftp
              command: /usr/libexec/openssh/sftp-server
          sshd_match_rules:
            - name: user_acme
              state: present
              conditions:
                - type: User
                  pattern: acme
              options:
                sshd_x11_forwarding: yes
                sshd_password_authentication: no
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
